### ISSUE TITLE
Can assign incompatible measures if they have some dimensions in common,

### ISSUE THREAD

**Issue by niklashallenfur** [jscheiny/safe-units#152]
The following, taken from the documentation
```
const error: Velocity = length.times(time);
// ERROR: A measure of m*s isn't assignable to a measure of m/s.
```
Gives a compile-time error.

But removing the `times` operation, making it just
```
const error: Velocity = length
```

Does not give a compile-time error, although the measures are clearly incompatible
Am I missing something? I have `strict` turned on in my tsconfig file.

Thanks otherwise for a fantastic library

**Comment by jscheiny** [comment]
Hey, thanks for bringing this to my attention! This actually exposes a pretty fundamental issue with the library that's gonna be pretty difficult to fix since typescript is structurally typed. I definitely should've thought of this sooner. This is going to take a while to resolve but my intuition right now is that we will need to make more stringent restrictions on custom dimensions that users can create in the library.

**Comment by jscheiny** [comment]
Actually this might be doable now. I had assumed that exact types would require a language update but it seems they are possible now! Will work on integrating this clever bit of type hackery into the code soon:

https://github.com/microsoft/TypeScript/issues/12936#issuecomment-524631270

**Comment by cloudify** [comment]
hello @jscheiny , thanks for this wonderful library - I think I just found another case where the library allows mixing units:

```ts
const a = length.times(time);
const b = length.plus(a); // <- this should not be allowed
```

I'm happy to help.

**Comment by phpcoder2022** [comment]
Hello. I joyed that you created so library and want help solve the problem. May be this [trick](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgS2AUQB5igXigWgExQA+uAjEVAAzlnF4DcAUA6JLIsAM5ZQDeDUUALYRgEAE4AuNkjRgANPygcIAYwD2cACZT4M9AoC+jZuGi7OAGTUqA1tz4CA2uagI4UGxBBqAZtM4AugD8UnAQAG7ijEZMEOhqYsBQKgA2AIYcXACyEBkArmIQADwAwgWFcMAucaJaXAAKaYkIaSlF5hwAfJ28imBiaqIqoppQhWmaGikgUABGYmla3MBieRCMAmB5sykIKmO5k3DTUHnsHFIASodTIKXlEJXmPQBkUADygkjt51a2ch4vL4oGUxBUquxOsYBOo4BwVnlhgkABRbHZ7A4TW5QcKtNahPKCWbiAFnJAXEEPJ7sACUvQEAmAAAsEBwAHRkzjcTlcDJQMKRMQbKAGBiihiw+FQYAAdzUOVEYi42DCMqgOXyhWReABPCEInEUjIBhpjElSWZhQgAGVVBpNMr+RA1RqOAUIMiAMy6pR2rRGkWmiUaKWRFLWJAgPBUFXO9W5N1a6M+4SKo0A5Sw7SkQNmkNJJq5EgUGNOl0J93I4sUFMGyRQAgmvNwtQpCBs8MAc2RsvldfZPKDwbhSU7CEiCvE3GRilThvjmuKern9eNUDen2+HT+NgBAHIV3vugo6ZgeivGGOJ3We3LJ0qg1eIPee0yrbasxxH+PnzewxHQGjb9r0VZFCzSasgyAA) help you.

**Comment by phpcoder2022** [comment]
I deleted odd hack from [my solution](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgS2AUQB5igXigWgExQA+uAjEVAAzlnF4DcAUA6JLIsAM5ZQDeDUUALYRgEAE4AuNkjRgANPygcIAYwD2cACZT4M9AoC+jZuGi7OAGTUqA1tz4CA2uagI4UGxBBqAZtM4AugD8UnAQAG7ijEZMEOhqYsBQKgA2AIYcXACyEBkArmIQADwAwgWFcMAucaJaXAAKaYkIaSlF5hwAfJ28imBiaqIqoppQhWmaGikgUABGYmla3MBieRCMAmB5sykIKmO5k3DTUHnsHFIASodTIKXlEJXmncYC6nAcK3nDCQAUWzs9gcJrcoOFWmtQnlBLNxHJTucpGUxBUquwAJS9AQCYAACwQHAAdGckFxsCTOBsoAYGDSGO9PlBgAB3NQ5URiMlQMLMqA5fKFX54eE8IQicRSMgGdGMBlJPGFCAAZVUGk0XJ5fNyHAKEF+AGYRUpVVpJdSZfSNIzIilrEgQHgqNhNfydYLHUbhBzJfDlO9tKRzbKrUkmrkSBQndyILzXbrfhGKJ7xZIoARpcGPmoUhBCbaAOa-FlslNEikcC2Wj5JfMISLs8TcX6KL0SrUC4qi1upqVQABkUAA8oIkO1zlZbPCAOTdqfdBSYzA9buMWv1lNF1kNzkWtcQbdF3GKlX+iuruv7jc2u2gR27i8HsNpRMWoA).
