### ISSUE TITLE
value in an unit

### ISSUE THREAD

**Issue by raoz** [jscheiny/safe-units#163]
Hello!

Would appreciate an escape-hatch to get the value in a particular unit, e.g.

`Measure.of(8, furlongs).valueIn(miles)` returns numeric `1`.

**Comment by jscheiny** [comment]
Hi @raoz,

This is possible right now via:

```ts
Measure.of(8, furlongs).over(miles).value
```

Does this solve your use case?

**Comment by raoz** [comment]
Hi @jscheiny,

Thanks, this does solve it for now, might make a pull request soon to add the `valueIn` sugar for clarity, if you don't mind.
