### ISSUE TITLE
Measure.of(<value>, bytes) yields value in bits

### ISSUE THREAD

**Issue by tymokvo** [jscheiny/safe-units#168]
Hello!

From the readme, I expected:
```typescript
console.log(Measure.of(72, bytes).toString());
```
to print `72 B`

but, the result is `576 b` as the underlying value created by `Measure.of` is in bits.

This is a _bit_ confusing as other higher order units behave as I would expect them to, e.g.:

```typescript
console.log(Measure.of(72, kilograms).toString());
```
yields `72 kg` rather than `72000 g`.

Using `v1.1.0` with Typescript `v4.3.5`.

**Comment by Darkhogg** [comment]
your kilogram example works because kilograms is the base unit of mass, but if you were to use pounds instead

```
console.log(Measure.of(72, pounds).toString());
// prints: 32.658650640000005 kg
```

you should use `.in` instead to print in a particular unit:
```
console.log(Measure.of(72, bytes).in(bytes));
console.log(Measure.of(72, kilograms).toString());
```

**Comment by tymokvo** [comment]
Makes sense! But still confusing. Maybe a reference to the SI base units in the documentation would help? For those of us (like me :grimacing: ) who haven't taken physics for a while?

NIST has a good reference [here](https://physics.nist.gov/cuu/Units/current.html), though it is US-centric. The [ISO standard](https://www.iso.org/standard/30669.html) is paywalled, unfortunately.

**Comment by jscheiny** [comment]
I know I'm a little late on this (😬), but there is a reference to this in the pre-existing documentation here: https://jscheiny.github.io/safe-units/builtin.html#base-units
