### ISSUE TITLE
Can I have the converted value as a just the number value, not a (value as string + symbol)?

### ISSUE THREAD

**Issue by rafaellehmkuhl** [jscheiny/safe-units#198]
First of all, nice library!

I'm working in [an application](https://github.com/bluerobotics/cockpit) and testing this library as the solution for our unit conversion system.

In our case, I need to be able to convert a value (let's say from meters to feet), but I need to be able to control the number of digits in this output value (as I will display this value in a constrained space).

Is there a way for to convert a value to another unit without the output being a string with the symbol added, but just the number value, so I can proper parse this to a string with the desired number of decimals (or precision)? Also, do I have a way to access the symbol of this converted value so I can also use it on the final presentation?

Ideally I would think on something like this:

```typescript
measurementInMeters = Measure.of(150, meters)
console.log(measurementInMeters.value) // 150
console.log(measurementInMeters.symbol) // 'm'

measurementInFeet = measurement.in(feet)
console.log(measurementInFeet.value) // 492.126
console.log(measurementInFeet.symbol) // 'ft'
```

Of course, for retro-compatibility purposes, other method names could be used.

If you're open to accept contributions, I would definitely be able to work on those features.

**Comment by rafaellehmkuhl** [comment]
I've actually found my way to do it in a functionality that was not documented:

```typescript
measurementInMeters = Measure.of(0.123456, meters)

console.log(measurementInMeters.in(meters) // 0.123456 m

const formattingOptions = { formatValue: (value) => value.toFixed(2) }

console.log(measurementInMeters.in(meters, formattingOptions) // 0.12 m
```

**Comment by jscheiny** [comment]
Glad you found the solution for this. There's documentation for this here: https://jscheiny.github.io/safe-units/measures.html#conversions Let me know if the documentation needs improvement.
